###test
GET {{url}}/test/sendMq
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/getById/5327
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/getAsk
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/update/ugcindex/ask/4780
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/getByAgg
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/getAskWeb
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/bulkAdd
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/delete
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/test/searchSBUserByInfo/455000
Accept: */*
Cache-Control: no-cache

###

###
GET {{url}}/base/savePoetry?id=1
Accept: application/json
Cache-Control: no-cache

###
GET {{url}}/base/saveContextSuggest?id=3&input=长安城头头白乌，夜飞延秋门上呼。又向人家啄大屋，屋底达官走避胡&category=poetry
Accept: application/json
Cache-Control: no-cache


###
GET {{url}}/suggest/term?text=山水
Accept: application/json
Cache-Control: no-cache


###
GET {{url}}/suggest/phrase?text=清溪深不
Accept: application/json
Cache-Control: no-cache

###
GET {{url}}/suggest/context?text=长安&category=location
Accept: application/json
Cache-Control: no-cache